### ISSUE TITLE
Tensors

### ISSUE THREAD

**Issue by debugwithGaganReddy** [KnutAM/tensors#17]
In the tensors Page, where you have an expression (Vtranspone. A. V), if the notation you gave where V = [ v1 v2 v3] is considered it is a 1 x 3, and vT would be 3x1 and if A is a matrix with 3 x 3, in that case VT*A*V would not satisfy matrix dimensions unless A is a scalar. Maybe it should be V*A*VT. If it is just for an example, then it is fine. If I am wrong please ignore/correct me.

**Comment by KnutAM** [comment]
You are absolutely right! (This is why I'm not such a fan of distinguishing between row and column vectors!)
I've redefined `v` to be a column vector on [Index notation](https://knutam.github.io/tensors/Theory/IndexNotation/), and highlighted that it is a column vector on [What are tensors?](https://knutam.github.io/tensors/Theory/TensorIntro/)
